# Generated by Django 5.1.3 on 2024-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='url_projeto',
            field=models.TextField(default='https://github.com/pontesvjp', max_length=100),
        ),
    ]
