# Generated by Django 5.1.3 on 2024-11-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_certificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
